### ISSUE TITLE
Web UI like Peplink InControl

### ISSUE THREAD

**Issue by relaxibus** [jasrusable/openwrt-configurator#2]
Hi, I'm really highly interested in your work. I'm looking for a central router management web ui to monitor and control routers deployed globally. Actually I'm using Peplink InControl: https://www.peplink.com/software/network-management-solution-incontrol-2/

Would you be open to talk more about?

**Comment by jasrusable** [comment]
Hi, yes, I'm open to talking more.

**Comment by relaxibus** [comment]
would we do it via email or Skype chat?

**Comment by jasrusable** [comment]
Email or on here would be best for me.

**Comment by relaxibus** [comment]
set you an email
